"""Merge flatc-generated *_generated.rs files into one foxglove.rs.

Each generated file looks like:

    // automatically generated by the FlatBuffers compiler, do not modify
    extern crate alloc;

    use crate::Foo_generated::*;     # zero or more inter-file imports
    use crate::Bar_generated::*;

    #[allow(unused_imports, dead_code)]
    pub mod foxglove {

      use crate::Foo_generated::*;   # same imports duplicated inside

      ... types / impls ...

    }  // end of pub mod foxglove

When you load 50 of these as separate top-level modules in one crate, the
inter-file glob imports each pull `foxglove` into scope, causing E0659
ambiguous-name errors (633 of them in our case).

Fix: drop the per-file `pub mod foxglove { ... }` wrapper and all the
`use crate::*_generated::*;` lines, then concat all bodies inside ONE
`pub mod foxglove { ... }` at crate root. All types live under
`crate::fbs_foxglove::foxglove::*` after this.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


def extract_body(src: str, namespace: str) -> str:
    """Return the bytes inside `pub mod <namespace> { ... }` for one file."""
    m = re.search(rf"pub\s+mod\s+{re.escape(namespace)}\s*\{{", src)
    if not m:
        raise ValueError(f"no `pub mod {namespace} {{` found")
    start = m.end()

    # walk forward tracking brace depth, ignoring braces inside strings or
    # line/block comments. flatc output is mechanical; we only need to be
    # robust against the patterns it actually emits.
    depth = 1
    i = start
    n = len(src)
    while i < n and depth > 0:
        ch = src[i]
        if ch == "/" and i + 1 < n and src[i + 1] == "/":
            # line comment
            nl = src.find("\n", i)
            i = n if nl == -1 else nl + 1
            continue
        if ch == "/" and i + 1 < n and src[i + 1] == "*":
            # block comment
            end = src.find("*/", i + 2)
            i = n if end == -1 else end + 2
            continue
        if ch == '"':
            # string literal — handle escapes
            i += 1
            while i < n:
                if src[i] == "\\":
                    i += 2
                elif src[i] == '"':
                    i += 1
                    break
                else:
                    i += 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1

    if depth != 0:
        raise ValueError("unbalanced braces in file")
    body = src[start:i]
    return body


def strip_inter_file_imports(body: str) -> str:
    out_lines = []
    for line in body.splitlines(keepends=True):
        stripped = line.strip()
        if re.fullmatch(r"use\s+crate::[A-Za-z0-9_]+_generated::\*\s*;", stripped):
            continue
        out_lines.append(line)
    return "".join(out_lines)


def merge(src_dir: Path, out_path: Path, namespace: str) -> int:
    files = sorted(src_dir.glob("*_generated.rs"))
    if not files:
        print(f"no *_generated.rs found under {src_dir}", file=sys.stderr)
        return 1

    parts: list[str] = []
    used = 0
    for f in files:
        try:
            body = extract_body(f.read_text(), namespace)
        except ValueError:
            continue
        body = strip_inter_file_imports(body)
        parts.append(f"// ===== from {f.name} =====\n{body}\n")
        used += 1

    if used == 0:
        print(f"no files contained `pub mod {namespace}`", file=sys.stderr)
        return 1

    # `discover` schemas reference `super::foxglove::Time` etc. — pull the
    # foxglove module into scope at the file level so `super::foxglove`
    # resolves from inside `pub mod discover`. No-op for foxglove itself.
    cross_use = "pub use crate::fbs_foxglove::foxglove;\n\n" if namespace != "foxglove" else ""
    header = (
        f"// AUTO-MERGED by tools/merge_fbs.py — DO NOT EDIT BY HAND.\n"
        f"// Inputs: src/fbs/*_generated.rs (verbatim flatc output)\n"
        f"// Namespace: {namespace}\n\n"
        "#![allow(unused_imports, dead_code, non_snake_case, clippy::all)]\n\n"
        "extern crate alloc;\n\n"
        f"{cross_use}"
        f"pub mod {namespace} {{\n\n"
    )
    footer = f"\n}} // pub mod {namespace}\n"
    out_path.write_text(header + "".join(parts) + footer)
    print(f"wrote {out_path} ({used} input files merged into `{namespace}`)")
    return 0


def main() -> int:
    src_dir = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])

    rc1 = merge(src_dir, out_dir / "fbs_foxglove.rs", "foxglove")
    rc2 = merge(src_dir, out_dir / "fbs_discover.rs", "discover")
    return rc1 or rc2


if __name__ == "__main__":
    sys.exit(main())
